export interface ScenarioRecord {
  title: string;
  commands: string[];
  passed: boolean;
  timingsMs: Record<string, number>;
  notes: string[];
}

export interface EnvInfo {
  gitVersion: string;
  bunVersion: string;
  os: string;
  date: string;
}

function fmtMs(ms: number): string {
  return `${ms.toFixed(1)} ms`;
}

function renderScenario(s: ScenarioRecord, index: number): string {
  const lines: string[] = [];
  lines.push(`## Scenario ${index}: ${s.title}`);
  lines.push("");
  lines.push(`**Result: ${s.passed ? "PASS" : "FAIL"}**`);
  lines.push("");
  if (s.commands.length > 0) {
    lines.push("Commands run:");
    lines.push("");
    lines.push("```");
    lines.push(...s.commands);
    lines.push("```");
    lines.push("");
  }
  const timingKeys = Object.keys(s.timingsMs);
  if (timingKeys.length > 0) {
    lines.push("Timings:");
    lines.push("");
    for (const key of timingKeys) {
      lines.push(`- ${key}: ${fmtMs(s.timingsMs[key] as number)}`);
    }
    lines.push("");
  }
  if (s.notes.length > 0) {
    lines.push("Notes:");
    lines.push("");
    for (const note of s.notes) {
      lines.push(`- ${note}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

export function renderResults(
  env: EnvInfo,
  scenarios: ScenarioRecord[],
): string {
  const allPassed = scenarios.every((s) => s.passed);
  const parts: string[] = [];
  parts.push("# M1.1 coordination-ref spike - results");
  parts.push("");
  parts.push(
    `Generated by \`bun spikes/coordination-ref/run.ts\` on ${env.date}. This file is ` +
      "produced by the run, not hand-written - re-running regenerates it (with fresh " +
      "timings and temp-directory paths).",
  );
  parts.push("");
  parts.push("## Environment");
  parts.push("");
  parts.push(`- git: ${env.gitVersion}`);
  parts.push(`- bun: ${env.bunVersion}`);
  parts.push(`- OS: ${env.os}`);
  parts.push("");
  parts.push(
    `## Overall: ${allPassed ? "ALL SCENARIOS PASSED" : "AT LEAST ONE SCENARIO FAILED"}`,
  );
  parts.push("");
  for (const [i, s] of scenarios.entries()) {
    parts.push(renderScenario(s, i + 1));
  }
  return `${parts.join("\n")}\n`;
}
